version: 0.2
phases: 
  install: 
    runtime-versions:
      golang: 1.12
      nodejs: 10
    commands:
      - sh scripts/install.sh
  pre_build: 
    commands:
      - sh scripts/test.sh
  build:
    commands:
      - sh scripts/build.sh
  post_build:
    commands:
      - sh scripts/deploy.sh
