service: go-sls-rest
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 256

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  rest:
    handler: bin/rest
    events:
      - http:
          path: items
          method: any
      - http:
          path: items/{id}
          method: any
